import "Layer.idl";

namespace D2DEngine{
	[version(1.0)]
	[marshaling_behavior(agile)]
	[threading(both)]
	[default_interface]
	runtimeclass LayerManager
	{
		LayerManager();
		
		Int32 LayerCount { get; };

		Layer GetLayer(Int32 index);
		void AddLayer(Layer layer);
		void RemoveLayer(Int32 index);
		void MoveLayer(Int32 fromIndex, Int32 toIndex);
		void Clear();
	}
}