import "BrushManager.idl";

namespace D2DEngine{
    enum RotateDirection {
        Left = 0,
        Right = 1
    };

    enum LayerType
    {
        Bitmap = 0,
        Vector = 1
    };    

    struct FillOptions
    {
        Windows.Foundation.Numerics.Vector4 Color;
        Single Opacity;
        Single Tolerance;
    };    

    enum AreaHandle
    {
        None = 0,
        TopLeft, TopCenter, TopRight,
        MiddleLeft, MiddleRight,
        BottomLeft, BottomCenter, BottomRight,
        Move
    };

    struct Area
    {
        Windows.Foundation.Rect Rect;
        Windows.Foundation.Rect OriginalRect;
        Boolean Active;
        Single HandleSize;
        Boolean IsOverlay;
        Single OverlayOpacity;
    };

    [version(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    [default_interface]
    runtimeclass Layer
    {
        Layer(String name, Int32 width, Int32 height, LayerType type);

        String Name { get; set; };
        Int32 Width { get; };
        Int32 Height { get; };
        LayerType Type { get; };
        Boolean Visible { get; set; };
        Double Opacity { get; set; };

        Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IBuffer> RenderToBufferAsync();

        void Resize(Int32 newWidth, Int32 newHeight, Boolean scaleContent);
        void Rotate(RotateDirection direction);
        void FlipHorizontal();
        void FlipVertical();

        void DrawStroke(Windows.Foundation.Collections.IVector<Windows.Foundation.Point> points, StrokeOptions options);
        void FillRect(Windows.Foundation.Rect rect, FillOptions options);
        void FillPath(Windows.Foundation.Collections.IVector<Windows.Foundation.Point> points, FillOptions options);
        void FloodFill(Int32 x, Int32 y, FillOptions options);

        AreaHandle HitTestSelectionHandle(Windows.Foundation.Point pt);
        void ResizeSelection(Windows.Foundation.Point newPt, AreaHandle handle);

        AreaHandle HitTestCropHandle(Windows.Foundation.Point pt);
        void ResizeCrop(Windows.Foundation.Point newPt, AreaHandle handle);
    }
}