name: "🕷️ Bug report"
description: Report errors or unexpected behavior
labels:
- Issue-Bug
- Needs-Triage
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/PaperHammer/VirtualPaper/issues) before filing a new one!
- type: input
  attributes:
    label: Virtual Paper version
    placeholder: 0.0.0
    description: Hover over system tray icon or look at Settings
  validations:
    required: true

- type: dropdown
  attributes:
    label: Installation method
    description: How / Where was installed from?
    multiple: true
    options:
      - GitHub
      - Microsoft Store
      - Dev build in Visual Studio
      - Other (please specify in "Steps to Reproduce")
  validations:
    required: true

- type: dropdown
  attributes:
    label: Running as admin
    description: Are you running PowerToys as Admin?
    options:
      - "Yes"
      - "No"

- type: dropdown
  attributes:
    label: Area(s) with issue?
    description: What things had an issue? Check all that apply.
    multiple: true
    options:
      - Gallery Module
      - Local Module
      - Account Module
      - Settings Module
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: We highly suggest including screenshots and a bug report log (System tray > Report bug).
    placeholder: Having detailed steps helps us reproduce the bug. 
  validations:
    required: true

- type: textarea
  attributes:
    label: ✔️ Expected Behavior
    placeholder: What were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: ❌ Actual Behavior
    placeholder: What happened instead?
  validations:
    required: false