# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: style_transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'style_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14style_transfer.proto\x12\x1dVirtualPaper.ML.StyleTransfer\"\x07\n\x05\x45mpty\"\x90\x01\n\x0cStyleRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\x12\n\nstyle_name\x18\x03 \x01(\t\x12\r\n\x05steps\x18\x04 \x01(\x05\x12\x1c\n\x14image_guidance_scale\x18\x05 \x01(\x02\x12\x16\n\x0eguidance_scale\x18\x06 \x01(\x02\"\xc2\x01\n\rProgressEvent\x12\r\n\x05stage\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_tile\x18\x02 \x01(\x05\x12\x13\n\x0btotal_tiles\x18\x03 \x01(\x05\x12\x14\n\x0c\x63urrent_step\x18\x04 \x01(\x05\x12\x13\n\x0btotal_steps\x18\x05 \x01(\x05\x12\x12\n\nelapsed_ms\x18\x06 \x01(\x03\x12\x14\n\x0c\x65stimated_ms\x18\x07 \x01(\x03\x12\x0f\n\x07message\x18\x08 \x01(\t\x12\x11\n\terror_msg\x18\t \x01(\t\"c\n\x12\x43\x61pabilityResponse\x12\x0f\n\x07\x62\x61\x63kend\x18\x01 \x01(\t\x12\x0f\n\x07vram_mb\x18\x02 \x01(\x05\x12\x15\n\rmax_tile_size\x18\x03 \x01(\x05\x12\x14\n\x0csupports_lcm\x18\x04 \x01(\x08\x32\xed\x01\n\rStyleTransfer\x12r\n\x13StylizeWithProgress\x12+.VirtualPaper.ML.StyleTransfer.StyleRequest\x1a,.VirtualPaper.ML.StyleTransfer.ProgressEvent0\x01\x12h\n\rGetCapability\x12$.VirtualPaper.ML.StyleTransfer.Empty\x1a\x31.VirtualPaper.ML.StyleTransfer.CapabilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'style_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=55
  _globals['_EMPTY']._serialized_end=62
  _globals['_STYLEREQUEST']._serialized_start=65
  _globals['_STYLEREQUEST']._serialized_end=209
  _globals['_PROGRESSEVENT']._serialized_start=212
  _globals['_PROGRESSEVENT']._serialized_end=406
  _globals['_CAPABILITYRESPONSE']._serialized_start=408
  _globals['_CAPABILITYRESPONSE']._serialized_end=507
  _globals['_STYLETRANSFER']._serialized_start=510
  _globals['_STYLETRANSFER']._serialized_end=747
# @@protoc_insertion_point(module_scope)
