# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import style_transfer_pb2 as style__transfer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in style_transfer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Grpc_StyleTransferServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StylizeWithProgress = channel.unary_stream(
                '/VirtualPaper.Grpc.Service.StyleTransfer.Grpc_StyleTransferService/StylizeWithProgress',
                request_serializer=style__transfer__pb2.StyleRequest.SerializeToString,
                response_deserializer=style__transfer__pb2.ProgressEvent.FromString,
                _registered_method=True)
        self.GetCapability = channel.unary_unary(
                '/VirtualPaper.Grpc.Service.StyleTransfer.Grpc_StyleTransferService/GetCapability',
                request_serializer=style__transfer__pb2.Empty.SerializeToString,
                response_deserializer=style__transfer__pb2.CapabilityResponse.FromString,
                _registered_method=True)


class Grpc_StyleTransferServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StylizeWithProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Grpc_StyleTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StylizeWithProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.StylizeWithProgress,
                    request_deserializer=style__transfer__pb2.StyleRequest.FromString,
                    response_serializer=style__transfer__pb2.ProgressEvent.SerializeToString,
            ),
            'GetCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapability,
                    request_deserializer=style__transfer__pb2.Empty.FromString,
                    response_serializer=style__transfer__pb2.CapabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VirtualPaper.Grpc.Service.StyleTransfer.Grpc_StyleTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VirtualPaper.Grpc.Service.StyleTransfer.Grpc_StyleTransferService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Grpc_StyleTransferService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StylizeWithProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/VirtualPaper.Grpc.Service.StyleTransfer.Grpc_StyleTransferService/StylizeWithProgress',
            style__transfer__pb2.StyleRequest.SerializeToString,
            style__transfer__pb2.ProgressEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VirtualPaper.Grpc.Service.StyleTransfer.Grpc_StyleTransferService/GetCapability',
            style__transfer__pb2.Empty.SerializeToString,
            style__transfer__pb2.CapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
