//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPaper.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualPaper.Properties.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        public static string AppUpdater_ActionButtonText_Completed {
            get {
                return ResourceManager.GetString("AppUpdater_ActionButtonText_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string AppUpdater_ActionButtonText_Downloading {
            get {
                return ResourceManager.GetString("AppUpdater_ActionButtonText_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装中... 的本地化字符串。
        /// </summary>
        public static string AppUpdater_ActionButtonText_Installing {
            get {
                return ResourceManager.GetString("AppUpdater_ActionButtonText_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续下载 的本地化字符串。
        /// </summary>
        public static string AppUpdater_ActionButtonText_Paused {
            get {
                return ResourceManager.GetString("AppUpdater_ActionButtonText_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string AppUpdater_ActionButtonText_Ready {
            get {
                return ResourceManager.GetString("AppUpdater_ActionButtonText_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余时间 的本地化字符串。
        /// </summary>
        public static string AppUpdater_SpeedText_Ready {
            get {
                return ResourceManager.GetString("AppUpdater_SpeedText_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成！ 的本地化字符串。
        /// </summary>
        public static string AppUpdater_StatusText_Completed {
            get {
                return ResourceManager.GetString("AppUpdater_StatusText_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法访问资源，尝试检查网络后重试 的本地化字符串。
        /// </summary>
        public static string AppUpdater_StatusText_DownloadFailed {
            get {
                return ResourceManager.GetString("AppUpdater_StatusText_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载... 的本地化字符串。
        /// </summary>
        public static string AppUpdater_StatusText_Downloading {
            get {
                return ResourceManager.GetString("AppUpdater_StatusText_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装完成！ 的本地化字符串。
        /// </summary>
        public static string AppUpdater_StatusText_Installed {
            get {
                return ResourceManager.GetString("AppUpdater_StatusText_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在安装更新... 的本地化字符串。
        /// </summary>
        public static string AppUpdater_StatusText_Installing {
            get {
                return ResourceManager.GetString("AppUpdater_StatusText_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载已暂停 的本地化字符串。
        /// </summary>
        public static string AppUpdater_StatusText_Paused {
            get {
                return ResourceManager.GetString("AppUpdater_StatusText_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备下载... 的本地化字符串。
        /// </summary>
        public static string AppUpdater_StatusText_Ready {
            get {
                return ResourceManager.GetString("AppUpdater_StatusText_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件校验失败，请重试下载 的本地化字符串。
        /// </summary>
        public static string AppUpdater_StatusText_VerifyFailed {
            get {
                return ResourceManager.GetString("AppUpdater_StatusText_VerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验资源完整性... 的本地化字符串。
        /// </summary>
        public static string AppUpdater_StatusText_Verifying {
            get {
                return ResourceManager.GetString("AppUpdater_StatusText_Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未完成安装，确定要退出吗？ 的本地化字符串。
        /// </summary>
        public static string AppUpdater_Update_DescriptionCancelQuestion_ForCompleted {
            get {
                return ResourceManager.GetString("AppUpdater_Update_DescriptionCancelQuestion_ForCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前更新正在下载中，是否确认中断并关闭？ 的本地化字符串。
        /// </summary>
        public static string AppUpdater_Update_DescriptionCancelQuestion_ForDownloading {
            get {
                return ResourceManager.GetString("AppUpdater_Update_DescriptionCancelQuestion_ForDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败；请尝试从以下地址下载安装程序手动更新:
        ///https://github.com/PaperHammer/VirtualPaper/releases 的本地化字符串。
        /// </summary>
        public static string AppUpdater_Update_ExceptionAppUpdateFail {
            get {
                return ResourceManager.GetString("AppUpdater_Update_ExceptionAppUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在进行更新 的本地化字符串。
        /// </summary>
        public static string AppUpdater_Update_TitleCancelQuestion {
            get {
                return ResourceManager.GetString("AppUpdater_Update_TitleCancelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Common_TextCancel {
            get {
                return ResourceManager.GetString("Common_TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Common_TextClose {
            get {
                return ResourceManager.GetString("Common_TextClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Common_TextConfirm {
            get {
                return ResourceManager.GetString("Common_TextConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Common_TextError {
            get {
                return ResourceManager.GetString("Common_TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试 的本地化字符串。
        /// </summary>
        public static string Common_TextRetry {
            get {
                return ResourceManager.GetString("Common_TextRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本！ 的本地化字符串。
        /// </summary>
        public static string Find_New_Verison {
            get {
                return ResourceManager.GetString("Find_New_Verison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有壁纸 的本地化字符串。
        /// </summary>
        public static string Systray_TextCloseAllWallpapers {
            get {
                return ResourceManager.GetString("Systray_TextCloseAllWallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气泡 的本地化字符串。
        /// </summary>
        public static string Systray_TextDEBubble {
            get {
                return ResourceManager.GetString("Systray_TextDEBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string Systray_TextDENone {
            get {
                return ResourceManager.GetString("Systray_TextDENone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态效果 的本地化字符串。
        /// </summary>
        public static string Systray_TextDynamicEffect {
            get {
                return ResourceManager.GetString("Systray_TextDynamicEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Systray_TextExit {
            get {
                return ResourceManager.GetString("Systray_TextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用屏保 的本地化字符串。
        /// </summary>
        public static string Systray_TextIsOnScrSaver {
            get {
                return ResourceManager.GetString("Systray_TextIsOnScrSaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复时显示登录界面 的本地化字符串。
        /// </summary>
        public static string Systray_TextIsRunningLock {
            get {
                return ResourceManager.GetString("Systray_TextIsRunningLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开主界面 的本地化字符串。
        /// </summary>
        public static string Systray_TextOpenApp {
            get {
                return ResourceManager.GetString("Systray_TextOpenApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 屏幕保护 的本地化字符串。
        /// </summary>
        public static string Systray_TextOpenScrSaverSet {
            get {
                return ResourceManager.GetString("Systray_TextOpenScrSaverSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停所有壁纸 的本地化字符串。
        /// </summary>
        public static string Systray_TextPauseWallpapers {
            get {
                return ResourceManager.GetString("Systray_TextPauseWallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报告漏洞 的本地化字符串。
        /// </summary>
        public static string Systray_TextReportBug {
            get {
                return ResourceManager.GetString("Systray_TextReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误，尝试重启程序以解决问题。若多次发生，请上报错误或联系开发者，并重新下载 的本地化字符串。
        /// </summary>
        public static string UIRunnerService_VirtualPaperExceptionGeneral {
            get {
                return ResourceManager.GetString("UIRunnerService_VirtualPaperExceptionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Paper 正在后台运行 的本地化字符串。
        /// </summary>
        public static string Virtual_Paper_isRunning {
            get {
                return ResourceManager.GetString("Virtual_Paper_isRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 愿你有美好的一天！ 的本地化字符串。
        /// </summary>
        public static string Virtual_Paper_isRunning_Greetings {
            get {
                return ResourceManager.GetString("Virtual_Paper_isRunning_Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生严重错误!
        ///Windows 资源管理器在过去 30 秒内重新启动两次！这可能是 Virtual Paper 与 Windows 或者其他桌面个性化软件之间出现冲突。为避免更多问题，已将所有壁纸终止。 的本地化字符串。
        /// </summary>
        public static string WndProcMsg_DescExplorerCrash {
            get {
                return ResourceManager.GetString("WndProcMsg_DescExplorerCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Paper 的本地化字符串。
        /// </summary>
        public static string WndProcMsg_TitleAppName {
            get {
                return ResourceManager.GetString("WndProcMsg_TitleAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到目标文件 的本地化字符串。
        /// </summary>
        public static string WpControl_TextFileNotFound {
            get {
                return ResourceManager.GetString("WpControl_TextFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要进行一些设置才能正常运行:
        ///1. 按Win+R键，打开运行。
        ///2. 在 &quot;运行 &quot;中输入SystemPropertiesPerformance.exe，点击 &quot;确定&quot;，打开性能选项。
        ///3. 启用/勾选 &quot;窗口内的动画控件和元素&quot;（如果已经勾选，则取消勾选）并应用。
        ///4. 点击 &quot;应用&quot;，然后按 &quot;确定&quot;，关闭该窗口。
        ///如果还是不行，关闭并重新启动或重启系统。(在某些 Windows 10 预览版本中不工作) 的本地化字符串。
        /// </summary>
        public static string WpControl_VirtualPaperExceptionWorkerWSetupFail {
            get {
                return ResourceManager.GetString("WpControl_VirtualPaperExceptionWorkerWSetupFail", resourceCulture);
            }
        }
    }
}
