; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define AppId "{{95F4CECE-7C7C-40E1-B485-07DA64D1905F}"
#define MyAppName "Virtual Paper"
#define MyAppVersion "0.4.0.0"
#define MyAppVersionText "0400"
#define MyAppPublisher "PaperHammer"
#define MyAppURL "https://github.com/PaperHammer/VirtualPaper"
#define MyAppExeName "VirtualPaper.exe"

[CustomMessages]
english.DeleteEverythigMsgBox=Do you want to delete data folder?
chinese.DeleteEverythigMsgBox=您要删除数据文件夹吗？
english.ClosingMsgBox=Application is running, do you want to close it?
chinese.ClosingMsgBox=应用程序正在运行，是否关闭？

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#AppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppMutex=Virtual:WALLPAPERSYSTEM
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppCopyright=Virtual@PaperHammer
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
OutputBaseFilename=virtualpaper_setup_x64_full_v{#MyAppVersionText}
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=Icons\virtualpaper.ico
WizardSmallImageFile=Themes\wizard_small.bmp
WizardImageFile=Themes\wizard_large.bmp
LicenseFile=License\LICENSE.txt
Uninstallable=true
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"; LicenseFile: "License\License.txt";
Name: "chinese"; MessagesFile: "Languages\ChineseSimplified.isl";

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
; Name: "windowsstartup";Description: "{cm:AutoStartProgram,{#MyAppName}}"

[Files]
Source: "..\src\VirtualPaper\bin\Release\net8.0-windows10.0.19041.0\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\src\VirtualPaper\bin\Release\net8.0-windows10.0.19041.0\*"; DestDir: "{app}"; Excludes: "*.pdb,*.xml"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; Root: HKA; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "VirtualPaper"; ValueData: """{app}\VirtualPaper.exe"""; Flags: uninsdeletevalue; Tasks:windowsstartup

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall; Check: AutoLaunch
;skipifsilent

[Code]
var
  isAlreadyInstalled: Boolean;
  UninstallProgressPage: TOutputProgressWizardPage;

// Read the uninstall string of the previously installed version from the registry.
function GetUninstallString(): String;
var
  sUnInstPath: String;
  sUnInstallString: String;
begin
  sUnInstPath := ExpandConstant(
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#emit SetupSetting("AppId")}_is1');
  sUnInstallString := '';
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString);
  Result := sUnInstallString;
end;

// Returns True if a previous version is already installed.
function IsUpgrade(): Boolean;
begin
  Result := (GetUninstallString() <> '');
end;

// Read the installation directory of the previously installed version from the registry.
function GetInstallDir(): String;
var
  sUnInstPath: String;
  sInstallLocation: String;
begin
  sUnInstPath := ExpandConstant(
    'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#emit SetupSetting("AppId")}_is1');
  sInstallLocation := '';
  if not RegQueryStringValue(HKLM, sUnInstPath, 'InstallLocation', sInstallLocation) then
    RegQueryStringValue(HKCU, sUnInstPath, 'InstallLocation', sInstallLocation);
  Result := sInstallLocation;
end;

procedure InitializeWizard();
var
  sOldDir: String;
  sNewDir: String;
begin
  if IsUpgrade() then
  begin
    sOldDir := GetInstallDir();
    sNewDir := sOldDir;
    StringChange(sNewDir, 'Virtual_Paper', 'Virtual Paper');
    if sNewDir <> sOldDir then
      WizardForm.DirEdit.Text := sNewDir;
  end;
end;

// Silently uninstall the previous version, show a progress page, and
// remove any leftover files in the old install directory.
// Return values:
//   1 - no previous version found (uninstall string is empty)
//   2 - failed to execute the uninstaller
//   3 - uninstalled successfully
function UnInstallOldVersion(): Integer;
var
  sUnInstallString: String;
  sInstallDir: String;
  iResultCode: Integer;
begin
  Result := 0;
  sUnInstallString := GetUninstallString();

  if sUnInstallString = '' then
  begin
    isAlreadyInstalled := False;
    Result := 1;
    Exit;
  end;

  // Save the old install directory before the uninstaller removes registry entries.
  sInstallDir := GetInstallDir();

  UninstallProgressPage := CreateOutputProgressPage(
    'Uninstalling previous version',
    'Please wait while the previous version is being removed...');
  UninstallProgressPage.Show;

  try
    UninstallProgressPage.SetText('Running uninstaller...', '');
    UninstallProgressPage.SetProgress(0, 4);

    sUnInstallString := RemoveQuotes(sUnInstallString);

    if Exec(sUnInstallString,
            '/VERYSILENT /NORESTART /SUPPRESSMSGBOXES',
            '', SW_HIDE, ewWaitUntilTerminated, iResultCode) then
    begin
      isAlreadyInstalled := True;
      UninstallProgressPage.SetProgress(2, 4);
      UninstallProgressPage.SetText('Uninstaller finished.', '');

      // Force-remove leftover files in the old install directory.
      // User data lives under {localappdata} and is not affected.
      if (sInstallDir <> '') and DirExists(sInstallDir) then
      begin
        UninstallProgressPage.SetText('Cleaning up leftover files...', sInstallDir);
        UninstallProgressPage.SetProgress(3, 4);
        DelTree(sInstallDir, True, True, True);
      end;

      UninstallProgressPage.SetProgress(4, 4);
      Result := 3;
    end
    else
    begin
      isAlreadyInstalled := True;
      UninstallProgressPage.SetText('Uninstaller encountered an error.', '');
      Result := 2;
    end;

  finally
    // Always hide the progress page to prevent the UI from appearing frozen.
    UninstallProgressPage.Hide;
  end;
end;

// Trigger the upgrade flow before files are installed.
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    if IsUpgrade() then
      UnInstallOldVersion();
  end;
end;

// Returns True when this is a fresh install (no previous version was found).
// Used to decide whether default wallpapers should be copied.
function ShouldInstallWallpapers: Boolean;
begin
  Result := not isAlreadyInstalled;
end;

// After a manual uninstall completes, ask the user whether to delete user data.
// This procedure is NOT called during an upgrade, so user data is always preserved on update.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    if SuppressibleMsgBox(
         ExpandConstant('{cm:DeleteEverythigMsgBox}') + ' ' +
         ExpandConstant('{localappdata}\{#MyAppName}') + ' ?',
         mbConfirmation, MB_YESNO, IDNO) = IDYES then
    begin
      DelTree(ExpandConstant('{localappdata}\{#MyAppName}'), True, True, True);
    end;
  end;
end;

// Before uninstalling, check whether the application is running.
// If it is, ask the user to confirm closing it before proceeding.
function InitializeUninstall(): Boolean;
var
  ErrorCode: Integer;
begin
  if CheckForMutexes('Virtual:WALLPAPERSYSTEM') then
  begin
    if SuppressibleMsgBox(ExpandConstant('{cm:ClosingMsgBox}'),
         mbConfirmation, MB_OKCANCEL, IDOK) = IDOK then
    begin
      ShellExec('open', 'taskkill.exe', '/f /im {#MyAppExeName}',
                '', SW_HIDE, ewWaitUntilTerminated, ErrorCode);
      Result := True;
    end
    else
      Result := False;
  end
  else
    // Application is not running; allow uninstall to proceed immediately.
    Result := True;
end;

// Check whether a specific version of the .NET Desktop Runtime is installed.
// Credits: https://github.com/domgho/InnoDependencyInstaller
// NetCoreCheck tool: https://github.com/dotnet/deployment-tools
function NetCoreNeedsInstall(version: String): Boolean;
var
  netcoreRuntime: String;
  resultCode: Integer;
begin
  netcoreRuntime := 'Microsoft.WindowsDesktop.App';
  Result := not (
    Exec(ExpandConstant('{tmp}\') + 'netcorecheck.exe',
         netcoreRuntime + ' ' + version,
         '', SW_HIDE, ewWaitUntilTerminated, resultCode)
    and (resultCode = 0)
  );
end;

// Returns True if the given command-line parameter was NOT passed to the installer.
function CmdLineParamNotExists(const Value: string): Boolean;
var
  I: Integer;
begin
  Result := True;
  for I := 1 to ParamCount do
    if CompareText(ParamStr(I), Value) = 0 then
    begin
      Result := False;
      Exit;
    end;
end;

// Returns True when the application should launch automatically after installation.
// Pass /NOAUTOLAUNCH on the command line to suppress auto-launch.
function AutoLaunch(): Boolean;
begin
  Result := CmdLineParamNotExists('/NOAUTOLAUNCH');
end;
