using System.IO.Compression;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCvSharp;
using VirtualPaper.ML.DynamicImage.Models;

namespace VirtualPaper.ML.DynamicImage {
    internal sealed record DynamicImageWebExport(
        string WebDirectory,
        string MotionConfigurationPath,
        string PackagePath);

    /// <summary>
    /// Builds a self-contained VirtualPaper web-wallpaper package. The
    /// background is warped continuously by its repaired depth texture while
    /// detected objects remain independent transparent layers.
    /// </summary>
    internal static partial class DynamicImageWebExporter {
        internal static DynamicImageWebExport Export(
            string imagePath,
            DynamicImageAnalysisResult analysis,
            string outputRoot,
            string backgroundPlatePath,
            string backgroundDepthPath,
            string diagnosticPreviewPath,
            IReadOnlyList<DynamicImageLayerExport> exports,
            CancellationToken ct) {

            ct.ThrowIfCancellationRequested();
            string webRoot = Path.Combine(outputRoot, "web");
            string assetRoot = Path.Combine(webRoot, "assets");
            string objectRoot = Path.Combine(assetRoot, "objects");
            Directory.CreateDirectory(objectRoot);

            string webBackgroundPath = Path.Combine(assetRoot, "background.png");
            string webDepthPath = Path.Combine(assetRoot, "background_depth.png");
            SaveRuntimeTexture(backgroundPlatePath, webBackgroundPath, 4096);
            SaveRuntimeTexture(backgroundDepthPath, webDepthPath, 1024);

            DynamicImageLayerPlan plan = analysis.LayerPlan;
            var exportLookup = exports.ToDictionary(item => item.LayerId, StringComparer.Ordinal);
            var objects = new List<MotionObject>();
            int objectIndex = 0;
            for (int layerIndex = 0; layerIndex < plan.Layers.Count; layerIndex++) {
                ct.ThrowIfCancellationRequested();
                DynamicImageLayer layer = plan.Layers[layerIndex];
                if (!layer.IsObject)
                    continue;

                DynamicImageLayerExport export = exportLookup[layer.Id];
                string fileName = $"object_{objectIndex:D2}.png";
                SaveRuntimeTexture(
                    export.VisibleCutoutPath,
                    Path.Combine(objectRoot, fileName),
                    4096);
                float medianDepth = Math.Clamp(layer.Depth.Median, 0f, 1f);
                objects.Add(new MotionObject(
                    layer.Id,
                    $"assets/objects/{fileName}",
                    layerIndex,
                    medianDepth,
                    0.9f + medianDepth * 0.1f));
                objectIndex++;
            }

            int safetyMargin = analysis.BackgroundPlate.SafetyMarginPixels;
            int maximumOffset = CalculateMaximumOffset(
                plan.Width,
                plan.Height,
                objects.Count,
                safetyMargin);
            var configuration = new MotionConfiguration(
                4,
                plan.Width,
                plan.Height,
                "assets/background.png",
                "assets/background_depth.png",
                safetyMargin,
                maximumOffset,
                0.15f,
                10f,
                0.3f,
                1.5f,
                0.9f,
                2.4f,
                objects);

            string motionPath = Path.Combine(webRoot, "motion.json");
            File.WriteAllText(
                motionPath,
                JsonSerializer.Serialize(
                    configuration,
                    MotionJsonContext.Default.MotionConfiguration));
            File.WriteAllText(Path.Combine(webRoot, "index.html"), IndexHtml);
            File.WriteAllText(Path.Combine(webRoot, "style.css"), StyleCss);
            File.WriteAllText(Path.Combine(webRoot, "player.js"), PlayerJavaScript);

            string previewPath = Path.Combine(assetRoot, "preview.jpg");
            SavePreview(imagePath, diagnosticPreviewPath, previewPath);
            var project = new WebProjectMetadata(
                $"{Path.GetFileNameWithoutExtension(imagePath)} - Dynamic",
                "AI layered dynamic wallpaper generated by VirtualPaper.",
                "VirtualPaper",
                "dynamic;ai;depth;parallax",
                "index.html",
                "assets/preview.jpg");
            File.WriteAllText(
                Path.Combine(webRoot, "project.json"),
                JsonSerializer.Serialize(project, MotionJsonContext.Default.WebProjectMetadata));

            ct.ThrowIfCancellationRequested();
            string packagePath = Path.Combine(outputRoot, "dynamic_wallpaper.zip");
            if (File.Exists(packagePath))
                File.Delete(packagePath);
            ZipFile.CreateFromDirectory(
                webRoot,
                packagePath,
                CompressionLevel.Optimal,
                includeBaseDirectory: false);
            return new DynamicImageWebExport(webRoot, motionPath, packagePath);
        }

        internal static int CalculateMaximumOffset(
            int width,
            int height,
            int objectCount,
            int safetyMarginPixels) {

            if (objectCount > 0 && safetyMarginPixels > 0) {
                int reserve = Math.Max(4, (int)Math.Ceiling(safetyMarginPixels * 0.125));
                return Math.Max(0, safetyMarginPixels - reserve);
            }

            return Math.Clamp(
                (int)Math.Round(Math.Min(width, height) * 0.008),
                8,
                48);
        }

        private static void SavePreview(string imagePath, string fallbackPath, string outputPath) {
            using Mat source = Cv2.ImRead(imagePath, ImreadModes.Color);
            if (source.Empty()) {
                File.Copy(fallbackPath, outputPath, overwrite: true);
                return;
            }

            const int maximumSide = 1280;
            double scale = Math.Min(1d, maximumSide / (double)Math.Max(source.Width, source.Height));
            using var preview = new Mat();
            if (scale < 1d) {
                Cv2.Resize(
                    source,
                    preview,
                    new Size(
                        Math.Max(1, (int)Math.Round(source.Width * scale)),
                        Math.Max(1, (int)Math.Round(source.Height * scale))),
                    interpolation: InterpolationFlags.Area);
            }
            else {
                source.CopyTo(preview);
            }

            if (!Cv2.ImWrite(outputPath, preview, [new ImageEncodingParam(ImwriteFlags.JpegQuality, 88)]))
                throw new IOException($"Failed to save web preview: {outputPath}");
        }

        internal static void SaveRuntimeTexture(
            string sourcePath,
            string outputPath,
            int maximumSide) {

            using Mat source = Cv2.ImRead(sourcePath, ImreadModes.Unchanged);
            if (source.Empty())
                throw new IOException($"Failed to load runtime texture: {sourcePath}");

            double scale = Math.Min(1d, maximumSide / (double)Math.Max(source.Width, source.Height));
            if (scale >= 1d) {
                File.Copy(sourcePath, outputPath, overwrite: true);
                return;
            }

            using var resized = new Mat();
            Cv2.Resize(
                source,
                resized,
                new Size(
                    Math.Max(1, (int)Math.Round(source.Width * scale)),
                    Math.Max(1, (int)Math.Round(source.Height * scale))),
                interpolation: InterpolationFlags.Area);
            if (!Cv2.ImWrite(
                outputPath,
                resized,
                [new ImageEncodingParam(ImwriteFlags.PngCompression, 4)])) {
                throw new IOException($"Failed to save runtime texture: {outputPath}");
            }
        }

        internal sealed record MotionConfiguration(
            int Version,
            int SourceWidth,
            int SourceHeight,
            string BackgroundTexture,
            string BackgroundDepthTexture,
            int SafetyMarginPixels,
            int MaximumOffsetPixels,
            float BackgroundMotionFactor,
            float IdlePeriodSeconds,
            float MotionResponseSeconds,
            float IdleTransitionSeconds,
            float PointerRange,
            float MaximumMotionSpeed,
            IReadOnlyList<MotionObject> Objects);

        internal sealed record MotionObject(
            string Id,
            string Texture,
            int BackToFrontIndex,
            float Depth,
            float MotionFactor);

        internal sealed record WebProjectMetadata(
            string Title,
            string Description,
            string Authors,
            string Tags,
            string File,
            string Preview);

        [JsonSerializable(typeof(MotionConfiguration))]
        [JsonSerializable(typeof(WebProjectMetadata))]
        [JsonSourceGenerationOptions(
            PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
            WriteIndented = true)]
        internal sealed partial class MotionJsonContext : JsonSerializerContext;

        private const string IndexHtml = """
            <!doctype html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width,initial-scale=1">
              <meta http-equiv="Cache-Control" content="no-cache">
              <title>VirtualPaper Dynamic Image</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
              <main id="stage" aria-label="Dynamic wallpaper">
                <canvas id="background"></canvas>
                <div id="objects" aria-hidden="true"></div>
                <div id="loading">Loading dynamic image…</div>
              </main>
              <script src="player.js"></script>
            </body>
            </html>
            """;

        private const string StyleCss = """
            :root { color-scheme: dark; }
            * { box-sizing: border-box; }
            html, body, #stage { width: 100%; height: 100%; margin: 0; overflow: hidden; }
            body { background: #05070d; }
            #stage { position: relative; isolation: isolate; }
            #background, #objects, .motion-object {
              position: absolute;
              inset: 0;
              width: 100%;
              height: 100%;
            }
            #background { display: block; z-index: 0; }
            #objects { z-index: 1; pointer-events: none; }
            .motion-object {
              object-fit: cover;
              will-change: transform;
              transform-origin: center center;
              backface-visibility: hidden;
            }
            #loading {
              position: absolute;
              inset: 0;
              z-index: 2;
              display: grid;
              place-items: center;
              color: rgba(255,255,255,.72);
              font: 14px/1.4 system-ui, sans-serif;
              background: #05070d;
              transition: opacity .35s ease;
            }
            #stage.ready #loading { opacity: 0; pointer-events: none; }
            """;

        private const string PlayerJavaScript = """
            (() => {
              'use strict';

              const stage = document.getElementById('stage');
              const canvas = document.getElementById('background');
              const objectHost = document.getElementById('objects');
              const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
              let config;
              let glState;
              let pointerTarget = { x: 0, y: 0 };
              let current = { x: 0, y: 0 };
              let velocity = { x: 0, y: 0 };
              let lastPointerAt = -Infinity;
              let previousFrameAt;
              let maximumScreenOffset = 0;

              const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

              function smoothDamp(value, target, speed, response, maximumSpeed, elapsed) {
                const smoothTime = Math.max(0.05, response);
                const omega = 2 / smoothTime;
                const step = omega * elapsed;
                const decay = 1 / (1 + step + 0.48 * step * step + 0.235 * step * step * step);
                const originalTarget = target;
                let change = value - target;
                const maximumChange = Math.max(0.01, maximumSpeed) * smoothTime;
                change = clamp(change, -maximumChange, maximumChange);
                target = value - change;
                const temporary = (speed + omega * change) * elapsed;
                let nextSpeed = (speed - omega * temporary) * decay;
                let nextValue = target + (change + temporary) * decay;
                if ((originalTarget - value > 0) === (nextValue > originalTarget)) {
                  nextValue = originalTarget;
                  nextSpeed = 0;
                }
                return { value: nextValue, speed: nextSpeed };
              }

              function createObjects() {
                for (const item of config.objects) {
                  const image = new Image();
                  image.className = 'motion-object';
                  image.src = item.texture;
                  image.alt = '';
                  image.dataset.motionFactor = String(item.motionFactor);
                  image.style.zIndex = String(item.backToFrontIndex);
                  objectHost.appendChild(image);
                }
              }

              function updateScale() {
                const coverScale = Math.max(
                  innerWidth / config.sourceWidth,
                  innerHeight / config.sourceHeight);
                maximumScreenOffset = config.maximumOffsetPixels * coverScale;
              }

              function resizeCanvas() {
                const requestedDpr = Math.min(devicePixelRatio || 1, 2);
                const cssPixels = Math.max(1, innerWidth * innerHeight);
                const maximumCanvasPixels = 3840 * 2160;
                const budgetDpr = Math.sqrt(maximumCanvasPixels / cssPixels);
                const dpr = Math.min(requestedDpr, Math.max(1, budgetDpr));
                const width = Math.max(1, Math.round(innerWidth * dpr));
                const height = Math.max(1, Math.round(innerHeight * dpr));
                if (canvas.width !== width || canvas.height !== height) {
                  canvas.width = width;
                  canvas.height = height;
                }
                glState?.gl.viewport(0, 0, width, height);
                updateScale();
              }

              function loadImage(path) {
                return new Promise((resolve, reject) => {
                  const image = new Image();
                  image.onload = () => resolve(image);
                  image.onerror = () => reject(new Error(`Failed to load ${path}`));
                  image.src = path;
                });
              }

              function compile(gl, type, source) {
                const shader = gl.createShader(type);
                gl.shaderSource(shader, source);
                gl.compileShader(shader);
                if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS))
                  throw new Error(gl.getShaderInfoLog(shader) || 'Shader compilation failed');
                return shader;
              }

              function createProgram(gl) {
                const vertex = compile(gl, gl.VERTEX_SHADER, `
                  attribute vec2 a_position;
                  varying vec2 v_uv;
                  void main() {
                    v_uv = (a_position + 1.0) * 0.5;
                    gl_Position = vec4(a_position, 0.0, 1.0);
                  }
                `);
                const fragment = compile(gl, gl.FRAGMENT_SHADER, `
                  precision mediump float;
                  uniform sampler2D u_image;
                  uniform sampler2D u_depth;
                  uniform vec2 u_viewSize;
                  uniform vec2 u_imageSize;
                  uniform vec2 u_motion;
                  uniform vec2 u_maxShift;
                  uniform float u_backgroundFactor;
                  varying vec2 v_uv;

                  void main() {
                    float viewAspect = u_viewSize.x / u_viewSize.y;
                    float imageAspect = u_imageSize.x / u_imageSize.y;
                    vec2 visibleRange = vec2(1.0);
                    if (viewAspect > imageAspect)
                      visibleRange.y = imageAspect / viewAspect;
                    else
                      visibleRange.x = viewAspect / imageAspect;

                    vec2 uv = (v_uv - 0.5) * visibleRange + 0.5;
                    float depth = texture2D(u_depth, uv).r;
                    float depthFactor = mix(0.12, u_backgroundFactor, smoothstep(0.0, 1.0, depth));
                    uv -= u_motion * u_maxShift * depthFactor;
                    gl_FragColor = texture2D(u_image, clamp(uv, vec2(0.001), vec2(0.999)));
                  }
                `);
                const program = gl.createProgram();
                gl.attachShader(program, vertex);
                gl.attachShader(program, fragment);
                gl.linkProgram(program);
                if (!gl.getProgramParameter(program, gl.LINK_STATUS))
                  throw new Error(gl.getProgramInfoLog(program) || 'Shader link failed');
                return program;
              }

              function createTexture(gl, image, unit) {
                const texture = gl.createTexture();
                gl.activeTexture(gl.TEXTURE0 + unit);
                gl.bindTexture(gl.TEXTURE_2D, texture);
                gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
                gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
                gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, image);
                return texture;
              }

              async function initializeWebGl() {
                const gl = canvas.getContext('webgl', {
                  alpha: false,
                  antialias: false,
                  powerPreference: 'high-performance'
                });
                if (!gl) throw new Error('WebGL is unavailable');
                const [background, depth] = await Promise.all([
                  loadImage(config.backgroundTexture),
                  loadImage(config.backgroundDepthTexture)
                ]);
                const program = createProgram(gl);
                gl.useProgram(program);
                const buffer = gl.createBuffer();
                gl.bindBuffer(gl.ARRAY_BUFFER, buffer);
                gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([
                  -1, -1, 1, -1, -1, 1,
                  -1, 1, 1, -1, 1, 1
                ]), gl.STATIC_DRAW);
                const position = gl.getAttribLocation(program, 'a_position');
                gl.enableVertexAttribArray(position);
                gl.vertexAttribPointer(position, 2, gl.FLOAT, false, 0, 0);
                createTexture(gl, background, 0);
                createTexture(gl, depth, 1);
                gl.uniform1i(gl.getUniformLocation(program, 'u_image'), 0);
                gl.uniform1i(gl.getUniformLocation(program, 'u_depth'), 1);
                gl.uniform2f(
                  gl.getUniformLocation(program, 'u_imageSize'),
                  config.sourceWidth,
                  config.sourceHeight);
                gl.uniform2f(
                  gl.getUniformLocation(program, 'u_maxShift'),
                  config.maximumOffsetPixels / config.sourceWidth,
                  config.maximumOffsetPixels / config.sourceHeight);
                gl.uniform1f(
                  gl.getUniformLocation(program, 'u_backgroundFactor'),
                  config.backgroundMotionFactor);
                glState = {
                  gl,
                  program,
                  motion: gl.getUniformLocation(program, 'u_motion'),
                  viewSize: gl.getUniformLocation(program, 'u_viewSize')
                };
              }

              function drawBackground() {
                if (!glState) return;
                const { gl, motion, viewSize } = glState;
                gl.uniform2f(viewSize, canvas.width, canvas.height);
                gl.uniform2f(motion, current.x, -current.y);
                gl.drawArrays(gl.TRIANGLES, 0, 6);
              }

              function animate(timeMilliseconds) {
                const time = timeMilliseconds / 1000;
                const elapsed = previousFrameAt === undefined
                  ? 1 / 60
                  : Math.min(1 / 15, Math.max(1 / 240, (timeMilliseconds - previousFrameAt) / 1000));
                previousFrameAt = timeMilliseconds;

                const phase = time * Math.PI * 2 / config.idlePeriodSeconds;
                const idle = reducedMotion
                  ? { x: 0, y: 0 }
                  : {
                      x: Math.sin(phase) * 0.66 + Math.sin(phase * 0.37 + 1.4) * 0.12,
                      y: Math.cos(phase * 0.79 + 0.35) * 0.42 + Math.sin(phase * 0.31) * 0.08
                    };
                const inactiveSeconds = (timeMilliseconds - lastPointerAt) / 1000;
                const transitionSeconds = Math.max(0.1, config.idleTransitionSeconds || 1.5);
                const blendPosition = clamp((inactiveSeconds - 1.2) / transitionSeconds, 0, 1);
                const idleBlend = blendPosition * blendPosition * (3 - 2 * blendPosition);
                const targetX = pointerTarget.x + (idle.x - pointerTarget.x) * idleBlend;
                const targetY = pointerTarget.y + (idle.y - pointerTarget.y) * idleBlend;
                const responseSeconds = reducedMotion
                  ? 0.18
                  : Math.max(0.05, config.motionResponseSeconds || 0.3);
                const maximumSpeed = Math.max(0.1, config.maximumMotionSpeed || 2.4);
                const nextX = smoothDamp(
                  current.x, targetX, velocity.x, responseSeconds, maximumSpeed, elapsed);
                const nextY = smoothDamp(
                  current.y, targetY, velocity.y, responseSeconds, maximumSpeed, elapsed);
                current.x = nextX.value;
                current.y = nextY.value;
                velocity.x = nextX.speed;
                velocity.y = nextY.speed;
                drawBackground();
                for (const image of objectHost.children) {
                  const factor = Number(image.dataset.motionFactor || 0.6);
                  const x = current.x * maximumScreenOffset * factor;
                  const y = current.y * maximumScreenOffset * factor;
                  image.style.transform = `translate3d(${x.toFixed(3)}px, ${y.toFixed(3)}px, 0)`;
                }
                requestAnimationFrame(animate);
              }

              addEventListener('pointermove', event => {
                let x = clamp(event.clientX / Math.max(1, innerWidth) * 2 - 1, -1, 1);
                let y = clamp(event.clientY / Math.max(1, innerHeight) * 2 - 1, -1, 1);
                const length = Math.hypot(x, y);
                if (length > 1) {
                  x /= length;
                  y /= length;
                }
                const range = clamp(config.pointerRange || 0.9, 0.1, 1);
                pointerTarget.x = x * range;
                pointerTarget.y = y * range;
                lastPointerAt = performance.now();
              }, { passive: true });
              addEventListener('pointerleave', () => {
                lastPointerAt = performance.now();
              });
              addEventListener('visibilitychange', () => {
                previousFrameAt = undefined;
              });
              addEventListener('resize', resizeCanvas, { passive: true });

              fetch('motion.json', { cache: 'no-store' })
                .then(response => {
                  if (!response.ok) throw new Error(`Motion config HTTP ${response.status}`);
                  return response.json();
                })
                .then(async value => {
                  config = value;
                  createObjects();
                  try {
                    await initializeWebGl();
                  } catch (error) {
                    console.error(error);
                    canvas.style.background = `center / cover no-repeat url("${config.backgroundTexture}")`;
                  }
                  resizeCanvas();
                  stage.classList.add('ready');
                  requestAnimationFrame(animate);
                })
                .catch(error => {
                  console.error(error);
                  document.getElementById('loading').textContent = 'Unable to load dynamic wallpaper';
                });
            })();
            """;
    }
}
